#!/usr/bin/env python3
"""Generate CRIF invocable smoketest Apex script."""
import re
from pathlib import Path

def main():
    base_path = Path(__file__).parent.parent
    invocable_class_path = base_path / 'force-app' / 'main' / 'default' / 'classes' / 'CrifMockSearchInvocable.cls'

    with open(invocable_class_path, encoding='utf-8') as f:
        apex_code = f.read()

    # Extract invocable method name (handle multi-line @InvocableMethod)
    method_match = re.search(r'@InvocableMethod\s*\([^)]+\)\s*public\s+static\s+List<(\w+)>\s+(\w+)\s*\(List<(\w+)>\s+(\w+)\)', apex_code, re.DOTALL)
    if not method_match:
        # Try simpler pattern
        method_match = re.search(r'public\s+static\s+List<(\w+)>\s+(\w+)\s*\(List<(\w+)>\s+(\w+)\)', apex_code)
        if not method_match:
            print("ERROR: Could not find @InvocableMethod")
            return

    response_class = method_match.group(1)
    method_name = method_match.group(2)
    request_class = method_match.group(3)
    param_name = method_match.group(4)

    print(f"Found invocable method: {method_name}")
    print(f"  Request class: {request_class}")
    print(f"  Response class: {response_class}")

    # Extract request class field names
    request_fields = {}
    request_class_match = re.search(rf'public\s+class\s+{request_class}\s*\{{(.*?)\}}', apex_code, re.DOTALL)
    if request_class_match:
        request_body = request_class_match.group(1)
        for field_match in re.finditer(r'@InvocableVariable[^\n]*\n\s*public\s+(\w+)\s+(\w+)\s*;', request_body):
            field_type = field_match.group(1)
            field_name = field_match.group(2)
            request_fields[field_name] = field_type
            print(f"  Request field: {field_name} ({field_type})")

    # Generate smoketest Apex
    smoketest_apex = f'''// ============================================================================
// CRIF Mock Invocable - End-to-End Smoketest
// ============================================================================
// Auto-generated by gen_crif_invocable_smoketest.py
// ============================================================================

// Test VAT number (can be overridden via env but not supported in anonymous Apex)
String testPiva = 'IT01234567890';

// Create request
CrifMockSearchInvocable.{request_class} req = new CrifMockSearchInvocable.{request_class}();
req.piva = testPiva;
'''

    # Set optional fields if they exist
    if 'includeDataPacketList' in request_fields:
        smoketest_apex += "req.includeDataPacketList = true;\n"
    if 'dataPacketListCsv' in request_fields:
        smoketest_apex += "req.dataPacketListCsv = 'atecoClassification,ecofin,operatingResults,employees,contacts,mail,pec,webAndSocial';\n"
    if 'page' in request_fields:
        smoketest_apex += "req.page = 0;\n"
    if 'size' in request_fields:
        smoketest_apex += "req.size = 15;\n"
    if 'acceptLanguage' in request_fields:
        smoketest_apex += "req.acceptLanguage = 'it-IT';\n"

    smoketest_apex += f'''
// Invoke method
List<CrifMockSearchInvocable.{request_class}> requests = new List<CrifMockSearchInvocable.{request_class}>{{req}};
List<CrifMockSearchInvocable.{response_class}> responses = CrifMockSearchInvocable.{method_name}(requests);

// Extract response
CrifMockSearchInvocable.{response_class} resp = responses[0];

// Print results
if (resp.tokenHttpStatus != null) {{
    System.debug('TOKEN HTTP STATUS: ' + resp.tokenHttpStatus);
}}
if (resp.searchHttpStatus != null) {{
    System.debug('SEARCH HTTP STATUS: ' + resp.searchHttpStatus);
}}

// Construct E2E JSON
Map<String, Object> e2eData = new Map<String, Object>();
e2eData.put('tokenHttpStatus', resp.tokenHttpStatus);
e2eData.put('searchHttpStatus', resp.searchHttpStatus);
e2eData.put('error', resp.error);
e2eData.put('vat11', resp.vat11);

String e2eJson = JSON.serialize(e2eData);
System.debug('E2E_JSON:' + e2eJson);

// Print error if present
if (String.isNotBlank(resp.error)) {{
    System.debug('ERROR: ' + resp.error);
}}
'''

    # Write smoketest file
    smoketest_path = base_path / 'scripts' / 'apex' / 'crif_invocable_smoketest.apex'
    smoketest_path.parent.mkdir(parents=True, exist_ok=True)
    with open(smoketest_path, 'w', encoding='utf-8') as f:
        f.write(smoketest_apex)

    print(f"\nGenerated smoketest: {smoketest_path}")

if __name__ == '__main__':
    main()
